### PR TITLE
Git style guide

### PR DESCRIPTION
**Pull request by iwi**
# Summary

As discussed, based on the style guide I showed you this branch tries to accomplish the following:
  - Add content to the Git style guide.
  - Re-structure some of the original content: I haven't taken anything out but I have re-structured the content separating it into an _introduction_ and the _style guide_ itself. I thought about separating parts of the style guide from general workflow/collaboration recommendations, but I haven't come up with a good idea on how to do it without breaking the current general structure.

# Review / Discuss
  - Check for typos / broken English :stuck_out_tongue: 
  - Discuss structure
  - Discuss content

### CODE REVIEW

**Comment by nathaneastwood** [comment]
@iwi I have reviewed the changes. Just a couple of things to note: 

- Campus specific text should be removed to say Government or similar. I recently pushed an update (https://github.com/datasciencecampus/coding-standards/commit/8c25983f9c8fcd8eca64f310772ae210c452bf05#diff-fd75300d36b3bdc7c012f2aca33bbda5) that removed this, so maybe you could take a look at incorporating those changes? It's not much.
- I think the following needs rewording. It kind of says the opposite to what the previous paragraph states. I agree with what you're saying (to an extent). You may also want to reference [this](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) link as it will help people better understand what you are talking about (or similar official documentation).
>It's always easier to squash two commits that have a similar purpose than to split one commit in two.
- [These two](https://github.com/iwi/coding-standards/blob/7b58c7cacf234d98b96089976d8ea67773e8a320/content/04-tools.Rmd#subject) are contradicting:
> use the imperative, present tense: "Change" not "Changed" nor "Changes"
do capitalise first letter
- With regards to versioning, I have no preference. However for R related stuff, people have a tendency these days to follow [Hadley's (it's probably not his) style](http://r-pkgs.had.co.nz/release.html#release-version)
- A little more on branch names: I quite like informative names such as `b/52` which would reference it as a bug and issue number 52. Others can be included for feature (`f`) and enhancement (`e`) and I'm sure the list could go on.

More generally I think it reads well and am happy with this contribution (thanks!!). There are some `git` commands included that people may not be as familiar with however - do you feel we should include longer examples of how to use these?

I'll await comment from @karetsu as well.

**Comment by iwi** [comment]
@nathaneastwood sounds good.

- Being campus specific was a concern I had, so that makes it a lot easier.
- On _squashing commits_ I'll make it a bit more explicit. I agree it lacks context. However, I would prefer to put [this](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) instead of the stackoverflow link.
- Versioning: happy to follow whatever option you like better, to be honest I don't have much experience on using it. Hadley's seems to be quite similar to SemVer. The only doubt I'd have is that adding a Hadley source makes it R centric and I thought the idea was to be more generic.
- I agree with you on the issue number on the branch naming, I'll expand including that. I'm not so sure about the `e` and `f` but I'm not against it.

About the unfamiliar `git` commands. I wouldn't include any how-tos on the Style Guide bit, but maybe links (as in the `git rebase -i`) or an extra with a workflow suggestion (like the one I shared with you). The only problem with the latter is that it might be too prescriptive in this context.

I'll wait for @karetsu 's comments.

**Comment by nathaneastwood** [comment]
@iwi 

- Yes that link seems reasonable for `squash`ing 👍 
- I agree that we don't want to make it too R centric. I guess this is maybe where we need to make a decision - one convention for all languages (probably easier) or separate conventions for separate languages (seems redundant to me).
- Happy to go with a simple convention if you would prefer, say, `bug/52`, I just like short names 😃 
- I agree that this isn't supposed to be a "how to". We don't want to be duplicating work that is already out there. Training materials are another thing and I suspect will become separate documents. Linking to references, however, I am all for that!

**Comment by iwi** [comment]
sorry... me doing stupid things

**Comment by iwi** [comment]
I'll PR again with some changes

**Pull request closed without merging**
